default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  host: localhost

development:
  <<: *default
  database: da_dev

production:
  <<: *default
  database: 'dashboards-app-database'

test:
  <<: *default
  database: da_test
